///////////////////////////////////////////////////////////
//  IReportRepository.cs
//  Implementation of the Interface IReportRepository
//  Generated by Enterprise Architect
//  Created on:      27-Nov-2025 06:13:30 PM
//  Original author: mario
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading.Tasks;

namespace LeadgerLink.Server.Repositories.Interfaces
{
    // Repository for report queries that return scalar metrics and file generation.
    public interface IReportRepository
    {
        // Get cost of goods sold for a store for the given year and month.
        Task<decimal> GetCOGSByStoreForMonthAsync(int storeId, int year, int month);

        // Get cost of goods sold for an organization for the given year and month.
        Task<decimal> GetCOGSByOrganizationForMonthAsync(int organizationId, int year, int month);

        // Get gross profit for an organization for the given year and month.
        Task<decimal> GetGrossProfitByOrganizationForMonthAsync(int organizationId, int year, int month);

        // Get gross profit for a store for the given year and month.
        Task<decimal> GetGrossProfitByStoreForMonthAsync(int storeId, int year, int month);

        // Get profit margin for an organization for the given year and month.
        Task<decimal> GetProfitMarginByOrganizationForMonthAsync(int organizationId, int year, int month);

        // Get profit margin for a store for the given year and month.
        Task<decimal> GetProfitMarginByStoreForMonthAsync(int storeId, int year, int month);

        // Placeholder report generation APIs (return raw file bytes).
        // Implementations should later generate the requested report and return file bytes.
        // For now these will return empty files (placeholders).
        Task<byte[]> GenerateReportPdfAsync(string reportId, int? organizationId = null, int? storeId = null);
        Task<byte[]> GenerateReportCsvAsync(string reportId, int? organizationId = null, int? storeId = null);
    }
}//end IReportRepository