///////////////////////////////////////////////////////////
//  IReportRepository.cs
//  Implementation of the Interface IReportRepository
//  Generated by Enterprise Architect
//  Created on:      27-Nov-2025 06:13:30 PM
//  Original author: mario
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading.Tasks;
using LeadgerLink.Server.Dtos;

namespace LeadgerLink.Server.Repositories.Interfaces
{
    // Repository for report queries that return scalar metrics and file generation.
    public interface IReportRepository
    {
        // Store-level
        Task<decimal> GetCOGSByStoreForMonthAsync(int storeId, int year, int month);
        Task<decimal> GetGrossProfitByStoreForMonthAsync(int storeId, int year, int month);
        Task<decimal> GetProfitMarginByStoreForMonthAsync(int storeId, int year, int month);
        Task<IEnumerable<ChartPointDto>> GetTopEmployeesBySalesAsync(int storeId, int topN);
        Task<TimeSeriesDto> GetStoreSalesSeriesAsync(int storeId, int months);
        Task<IEnumerable<ChartPointDto>> GetItemUtilizationAsync(int storeId, int topN);
        Task<IEnumerable<ChartPointDto>> GetInventoryByCategoryAsync(int storeId);
        Task<TransferCountsDto> GetInventoryTransferCountsAsync(int storeId, DateTime from, DateTime to);
        Task<IEnumerable<ChartPointDto>> GetTopProductsBySalesAsync(int storeId, int topN);

        // Organization-level aggregation
        Task<decimal> GetCOGSByOrganizationForMonthAsync(int organizationId, int year, int month);
        Task<decimal> GetGrossProfitByOrganizationForMonthAsync(int organizationId, int year, int month);
        Task<decimal> GetProfitMarginByOrganizationForMonthAsync(int organizationId, int year, int month);
        Task<TimeSeriesDto> GetOrganizationSalesSeriesAsync(int organizationId, int months);
        Task<IEnumerable<ChartPointDto>> GetItemUtilizationByOrganizationAsync(int organizationId, int topN);
        Task<IEnumerable<ChartPointDto>> GetInventoryByCategoryForOrganizationAsync(int organizationId);
        Task<TransferCountsDto> GetInventoryTransferCountsForOrganizationAsync(int organizationId, DateTime from, DateTime to);
        Task<IEnumerable<ChartPointDto>> GetTopProductsBySalesForOrganizationAsync(int organizationId, int topN);
        Task<IEnumerable<ChartPointDto>> GetStoreSalesContributionForOrganizationAsync(int organizationId, DateTime from, DateTime to);

        // Existing report generators
        Task<byte[]> GenerateReportPdfAsync(string reportId, int? organizationId = null, int? storeId = null);
        Task<byte[]> GenerateReportCsvAsync(string reportId, int? organizationId = null, int? storeId = null);

        // Current stock
        Task<byte[]> GenerateCurrentStockReportPdfAsync(int storeId);
        Task<byte[]> GenerateCurrentStockReportExcelAsync(int storeId);

        // Top Recipes & Sales
        Task<byte[]> GenerateTopRecipesSalesReportPdfAsync(int storeId);
        Task<byte[]> GenerateTopRecipesSalesReportExcelAsync(int storeId);

        // Top Employee
        Task<byte[]> GenerateTopEmployeeReportPdfAsync(int storeId);
        Task<byte[]> GenerateTopEmployeeReportExcelAsync(int storeId);

        // Sales Summary
        Task<byte[]> GenerateSalesSummaryReportPdfAsync(int storeId);
        Task<byte[]> GenerateSalesSummaryReportExcelAsync(int storeId);

        // Inventory Usage Trends
        Task<byte[]> GenerateInventoryUsageTrendsReportPdfAsync(int storeId);
        Task<byte[]> GenerateInventoryUsageTrendsReportExcelAsync(int storeId);

        // Monthly COGS report (organization-level): generated file outputs
        Task<byte[]> GenerateMonthlyCogsReportPdfAsync(int organizationId, int year, int month);
        Task<byte[]> GenerateMonthlyCogsReportExcelAsync(int organizationId, int year, int month);

        // Monthly Gross Profit & Profit Margin (organization-level): generated file outputs
        Task<byte[]> GenerateMonthlyGrossProfitReportPdfAsync(int organizationId, int year, int month);
        Task<byte[]> GenerateMonthlyGrossProfitReportExcelAsync(int organizationId, int year, int month);

        // Inventory Valuation report (organization-level): Excel output only
        Task<byte[]> GenerateInventoryValuationReportExcelAsync(int organizationId);

        // Sales By Recipe (organization-level): generated file outputs
        Task<byte[]> GenerateSalesByRecipeReportPdfAsync(int organizationId, int year, int month);
        Task<byte[]> GenerateSalesByRecipeReportExcelAsync(int organizationId, int year, int month);

        // Monthly Sales report (organization-level): generated file outputs
        Task<byte[]> GenerateMonthlySalesReportPdfAsync(int organizationId, int year, int month);
        Task<byte[]> GenerateMonthlySalesReportExcelAsync(int organizationId, int year, int month);
    }
}//end IReportRepository